### ISSUE TITLE
Get organized 

### ISSUE THREAD

**Issue by BobSaidHi** [BobSaidHi/MechWarfare2022DSCode#2]
- [x] When to meet - https://www.when2meet.com/?19155378-zOG4K
- [x] Review supplies
- [x] Review goals
- [x] Review plans & milestones

**Comment by KyleQ1** [comment]
Things that we have:
- The base of the robot has two AX-12A Motors
- Gun takes in probably a 9V battery
- Ammo
- ESP 32
- Battery Charger takes in Wall AC and outputs charge current 3:1000mA
- 3 Batteries rated 7.4V 1000mah 30-40c discharge
- 2 Batteries rated 11.1V 1000mah 25c discharge
- 3 PCB meant to take ESP 32 and two power sources
- 1 FPV camera including transmitter and antenna
- 1 Low noise power MOSFET for antenna
- 2 RPICam 
- 2 Logitech cams
- 1 USB-C cable
- 3 main circuit boards made in 2022 taking in two power 
- Lots of older circuit boards
- Lots of older parts from the team in the past
- MAX 14870 single brushed cd motor driver carier
- Arduino Mega, Arduino Uno, and Arduino Pro micro
- A buck-boost converter
- Opencm board?

Things that we need to do:
- Get serial connection to AX-12A motors
- Connect power to the gun and main motors of the robot
- Find out how the 2022 circuit board works
- Somehow get vision involved perhaps using the FPV kit given

**Comment by BobSaidHi** [comment]
We also have an opencm9.04

**Comment by BobSaidHi** [comment]
Another year, another organizational mess (Well it's not that bad)

**Comment by BobSaidHi** [comment]
OK good enough I guess.
